batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403161622
train_epochs: 1
train_workers: 20
vocab: w0+,F:MTrW1n7mJQ*KD'vGejLNX(HSbu.z6-aEy"cBhP9U;qxVCYk!fIo3&dt2g?4#5AOilpsRZ)/8
width: 128
