batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202403152352
train_epochs: 1000
train_workers: 20
vocab: nzj-cTS5?0QCtF/W*E'7g(p2+&4PXR9a8e;fvrwql.J,!udNV3xy)G1M#KZbAiO:D"Uo6msBHYhIkL
width: 128
